baseURL = "https://Anointing.netlify.app/"
languageCode = "en-us"
title = "Anointing"
paginate     = 10
googleAnalytics = "UA-123518521-4"
disqusShortname = "myfoliosite"

[params]
  dateform    = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  ProfilePicture = "../images/profilePicture.jpg"

  # Subtitle for home
  homeSubtitle = "Software Engineer 〣 Technical Writer 〣 Opensource Enthusiast"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Anointing | Software Engineer | Backend Engineer | Golang Developer | Rust Developer | Technical Writer| Golang, Rust, Python | Open Source Enthusiast"
  images = [""]

  enableRobotsTXT = true
  enableGitInfo   = false
  enableEmoji     = true
  enableMissingTranslationPlaceholders = false
  disableRSS     = true
  disableSitemap = false
  disable404     = false

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#151515"
  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [""]
  customJS  = []

[author]
  name = "Adetoye Anointing"

[permalinks]
  posts = "/:slug"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Adetoye Anointing"
    subtitle = "Software Engineer, Backend Engineer, Golang Developer, Rust Developer, Technical Writer and Opensource Enthusiast"
    keywords = "go, golang, rust, rust lang, software Engineer, Technical Writer, backend developer, backend development"
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "~/Anointing"
      logoHomeLink = "/"
    # or
    #Anointing
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # Social icons
  [[languages.en.params.social]]
    name = "twitter"
    url  = "https://twitter.com/Anointing"

  [[languages.en.params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/adetoye-anointing"

  [[languages.en.params.social]]
    name = "email"
    url  = "mailto:adetoyeanointing2002@gmail.com"

  [[languages.en.params.social]]
    name = "github"
    url  = "https://github.com/Anointinggg"

    # You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "https://blogs.gnome.org/Anointing"
      [[languages.en.menu.main]]
        identifier = "talks"
        name = "Talks"
        url = "/talks"
      [[languages.en.menu.main]]
        identifier = "works"
        name = "Works"
        url = "/works"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "WhoAmI"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "resume"
        name       = "Resume"
        url        = "https://docs.google.com/document/d/1pnIV27RFDnoHLjDYf2i93DfreUW682mny3ODPPKXTK4/edit?usp=sharing"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://blogs.gnome.org/Anointing"
  [[menu.main]]
    identifier = "talks"
    name       = "Talks"
    url        = "/talks"
  [[menu.main]]
    identifier = "works"
    name       = "Works"
    url        = "/works"
  [[menu.main]]
    identifier = "whoAmI"
    name       = "WhoAmI"
    url        = "/about"
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "https://docs.google.com/document/d/1pnIV27RFDnoHLjDYf2i93DfreUW682mny3ODPPKXTK4/edit?usp=sharing"

categories:
  - title: "Core Technologies"
    tags: ["Golang", "Rust", "Python"]
  #- title: "Infrastructure"
    #tags: ["Docker", "Kubernetes", "Terraform", "AWS/GCP", "CI/CD"]
  #- title: "Blockchain"
    #tags: ["Ethereum", "Solana", "Foundry", "Hardhat", "CosmWasm"]
