[[redirects]]
from = "/posts/"
to = "https://yorubad-dev-blog.netlify.app/"
status = 301
force = true

[[redirects]]
from = "https://yorubad-dev.netlify.app/posts/"
to = "https://yorubad-dev-blog.netlify.app/"
status = 301
force = true

[[redirects]]
from = "/blog/"
to = "https://yorubad-dev-blog.netlify.app/"
status = 301
force = true
